FROM registry.fedoraproject.org/fedora-toolbox:44

RUN dnf install -y --setopt=install_weak_deps=False \
      make \
      golang \
      curl \
      jq \
      python3 \
      cmake \
      ninja-build \
      gcc \
      gcc-c++ \
      git \
      autoconf \
      automake \
      libtool \
      perl \
      zlib-devel \
      openssl-devel \
      pam-devel \
      libselinux-devel \
      rpm-build \
      rpmdevtools \
      rpm-sign \
      gnupg2 \
      selinux-policy-devel \
      systemd-rpm-macros \
    && dnf clean all
