#!/usr/bin/env bash
# Build the qp-nebula sim BASE image: an unattended Fedora Server 44 install (UEFI)
# via kickstart into a qcow2 the node VMs clone as a copy-on-write backing file.
# Barebones - stock Fedora + ssh + net tools; the qp-nebula binary/cert/config are
# pushed per-node at run time. Idempotent (re-running rebuilds from scratch).
#
set -euo pipefail
LOG_TAG=base
. "$(dirname "$0")/common.sh"

# Host quirk (this dev box): /usr/bin/python3 is a non-distro build that omits the
# distro GI paths virt-install needs. Prepend them only if they exist (portable).
for p in /usr/lib/python3/dist-packages; do [ -d "$p" ] && export PYTHONPATH="$p${PYTHONPATH:+:$PYTHONPATH}"; done
for g in /usr/lib/x86_64-linux-gnu/girepository-1.0; do [ -d "$g" ] && export GI_TYPELIB_PATH="$g${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}"; done

# Fedora Server DVD ISO - point QPN_FEDORA_ISO at your copy (kept out of the repo;
# big binary). No default vendor path.
ISO_SRC="${QPN_FEDORA_ISO:-}"
[ -n "$ISO_SRC" ] || die "set QPN_FEDORA_ISO=/path/to/Fedora-Server-dvd-x86_64-44-*.iso"
[ -f "$ISO_SRC" ] || die "ISO not found: $ISO_SRC"

KS="$SIM/kickstart/base.ks.template"
RENDERED="$QPN_BUILD/base.ks"
ISO="$QPN_IMG_DIR/$(basename "$ISO_SRC")"

mkdir -p "$QPN_BUILD" "$(dirname "$QPN_KEY")"
[ -d "$QPN_IMG_DIR" ] || sudo install -d -o "$USER" -g libvirt -m 0711 "$QPN_IMG_DIR"
if [ ! -f "$ISO" ] || [ "$ISO_SRC" -nt "$ISO" ]; then
  log "staging ISO into $QPN_IMG_DIR"; cp -f "$ISO_SRC" "$ISO"
fi

# The gitignored lab key is generated by `make -C simulation provision-key` (the
# Makefile sentinels it and makes every VM target depend on it). Require it here.
[ -f "$QPN_KEY.pub" ] || die "provision key missing - run 'make -C simulation provision-key'"
PUB="$(cat "$QPN_KEY.pub")"
sed -e "s|{{SSH_PUBKEY}}|$PUB|" "$KS" > "$RENDERED"

$VIRSH destroy  "$DOM_PREFIX-base" 2>/dev/null || true
$VIRSH undefine "$DOM_PREFIX-base" --nvram 2>/dev/null || true
rm -f "$QPN_BASE"

log "installing Fedora Server 44 (unattended, ~10-15 min)..."
# virt-install can exit non-zero when the kickstart powers the VM off; verify after.
virt-install \
  --connect qemu:///system \
  --name "$DOM_PREFIX-base" \
  --memory 2048 --vcpus 2 \
  --disk path="$QPN_BASE",size=8,format=qcow2,bus=virtio \
  --location "$ISO" \
  --initrd-inject "$RENDERED" \
  --extra-args "inst.ks=file:/$(basename "$RENDERED") console=ttyS0,115200n8 inst.notmux" \
  --network network=default,model=virtio \
  --os-variant detect=on,require=off \
  --boot uefi \
  --graphics none --noautoconsole --wait -1 || true

$VIRSH dominfo "$DOM_PREFIX-base" >/dev/null 2>&1 || die "domain not created"
$VIRSH destroy "$DOM_PREFIX-base" 2>/dev/null || true
sudo chown "$USER:libvirt" "$QPN_BASE"; chmod 0644 "$QPN_BASE"

log "generalizing for cloning..."
virt-sysprep -q -a "$QPN_BASE" \
  --operations machine-id,ssh-hostkeys,bash-history,logfiles,tmp-files 2>/dev/null \
  || log "WARNING: virt-sysprep reported issues (continuing)"
# Keep the base domain definition out of the way - clones define their own.
$VIRSH undefine "$DOM_PREFIX-base" --nvram 2>/dev/null || true
log "done -> $QPN_BASE"
